# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy app source code
COPY . .

# Build the app
RUN npm run build

# Expose port if needed (not required for stdio transport; useful for debugging)
# EXPOSE 3000

# Run the MCP server
CMD [ "node", "build/index.js" ]
